### ISSUE TITLE
buffer output by plugin execution

### ISSUE THREAD

**Issue by delanym** [fabriciorby/maven-surefire-junit5-tree-reporter#15]
I can confirm the plugin is now (v1.0.0) buffering the output by class.
Would it be possible to buffer the output by plugin execution?
Or is this something Maven should be handling?

For example, currently a log might have a line
```
[INFO] --- maven-jar-plugin:3.2.2:jar (default-jar) @ wwgcommon ---
```
followed by
```
[INFO] |  +-- [OK] testUnpaidImport - 0.179s
[INFO] |  '-- [OK] testReplyImport - 0.002s
```

**Comment by fabriciorby** [comment]
Hello @delanym, unfortunately I think it's out of the scope of this plugin extension...

Today I could buffer it by class by doing some workaround, so maybe there could be another workaround to buffer by plugin execution, but, by the way Maven Surefire handles it, I think it's not ideal.

The problem is that the implemented extension has no access to the total list of classes/tests it would need to print, so it doesn't know when the tests are over in order to print it.

By the way, how is your setup in order to print it out of order? I should give it a try.

**Comment by delanym** [comment]
@fabriciorby yeah I've seen this with other plugins. All you need is a project with many modules and then build it with `mvn -T1C` to build multi-threaded. If you have 12 cores, it should build with 12 threads, and up to 12 modules at one time writing to logs. I can't offer my closed-source project, but maybe you could try with https://github.com/quarkusio/quarkus
